fix : src/components/shared/Card.shared.component.tsx(13,52): error TS6133: 'isHoverActive' is declared but its value is never read. src/components/shared/Slider.shared.component.tsx(1,8): e